### ISSUE TITLE
Crash starting iOs app only in production mode 

### ISSUE THREAD

**Issue by zupodaniel** [tiaanduplessis/react-native-modest-checkbox#10]
My app is crashing when starting but only in production mode. Do you have any tips about that?

When I remove the use of the plugin the crash stops.

--------------------------------------------
```
<CheckBox
                                checked={this.state.showOnlyHighRes}
                                labelBefore={true}
                                labelStyle={s.galleryQualitySelectorHint}
                                checkboxStyle={{width:45, height:30}}
                                containerStyle={{paddingHorizontal:5, paddingRight: 10}}
                                checkedImage={require('../assets/img/switchOn.png')} uncheckedImage={require('../assets/img/switchOff.png')}
                                label={'apenas imagens em alta resolução '}
                                onChange={this.showOnlyHighResChange.bind(this)}
                            />

```
--------------------------------------------

> Last Exception Backtrace:
> 0   CoreFoundation                	0x1824f2d8c __exceptionPreprocess + 228
> 1   libobjc.A.dylib               	0x1816ac5ec objc_exception_throw + 55
> 2   EasyFoto4U                    	0x104f76a08 RCTFatal + 447
> 3   EasyFoto4U                    	0x104f744c8 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 491
> 4   CoreFoundation                	0x1824fa580 __invoking___ + 143
> 5   CoreFoundation                	0x1823d9748 -[NSInvocation invoke] + 283
> 6   CoreFoundation                	0x1823de56c -[NSInvocation invokeWithTarget:] + 59
> 7   EasyFoto4U                    	0x104f8a454 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 491
> 8   EasyFoto4U                    	0x104fce8c8 facebook::react::invokeInner+ 1583304 (RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 259
> 9   EasyFoto4U                    	0x104fce628 invocation function for block in facebook::react::RCTNativeModule::invoke+ 1582632 (unsigned int, folly::dynamic&&, int) + 87
> 10  libdispatch.dylib             	0x181de4b24 _dispatch_call_block_and_release + 23
> 11  libdispatch.dylib             	0x181de4ae4 _dispatch_client_callout + 15
> 12  libdispatch.dylib             	0x181deea38 _dispatch_queue_serial_drain$VARIANT$mp + 607
> 13  libdispatch.dylib             	0x181def380 _dispatch_queue_invoke$VARIANT$mp + 335
> 14  libdispatch.dylib             	0x181defd4c _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 339
> 15  libdispatch.dylib             	0x181df811c _dispatch_workloop_worker_thread$VARIANT$mp + 667
> 16  libsystem_pthread.dylib       	0x182117e70 _pthread_wqthread + 859
> 17  libsystem_pthread.dylib       	0x182117b08 start_wqthread + 3

**Comment by tiaanduplessis** [comment]
@zupodaniel I believe this may be related to #11 . Please check if [v3.0.1](https://github.com/tiaanduplessis/react-native-modest-checkbox/releases/tag/v3.0.1) resolves the issue.

**Comment by zupodaniel** [comment]
Thanks, I will try soon.

**Comment by zupodaniel** [comment]
Now it's working. Thank you.
