### ISSUE TITLE
App crash in release mode when using 'View.propTypes.style'

### ISSUE THREAD

**Issue by naldyn** [tiaanduplessis/react-native-modest-checkbox#11]
{
  "name": "xyz",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@unpourtous/react-native-search-list": "^2.0.10",
    "moment": "^2.22.2",
    "react": "^16.4.0",
    "react-native": "^0.55.4",
    "react-native-animatable": "^1.3.0",
    "react-native-calendars": "^1.19.3",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^0.21.5",
    "react-native-elements": "^0.19.1",
    "react-native-event-listeners": "^1.0.3",
    "react-native-floating-action": "^1.10.1",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-material-bottom-navigation": "^1.0.0",
    "react-native-modal": "^6.1.0",
    "react-native-modal-selector": "0.0.27",
    "react-native-modest-checkbox": "^3.0.0",
    "react-native-phone-call": "^1.0.6",
    "react-native-popup-menu": "^0.13.1",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-signalr": "^1.0.6",
    "react-native-sms-android": "^0.4.1",
    "react-native-svg": "^6.3.1",
    "react-native-swiper": "^1.5.13",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.3.0",
    "realm": "^2.8.1",
    "victory-native": "^0.18.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.0-alpha.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by tiaanduplessis** [comment]
@naldyn this seems to be a issue on [react-native](https://github.com/facebook/react-native/issues/16542). Will update to use `ViewPropTypes.style`

**Comment by tiaanduplessis** [comment]
Closing in meantime.
