### ISSUE TITLE
Checkbox not updating checked when prop changes

### ISSUE THREAD

**Issue by dragonfire1119** [tiaanduplessis/react-native-modest-checkbox#12]
You had in 2.0.0 `componentDidUpdate` but in 3.0.0 you removed it. #9 that issue fix got totally undone on 3.0.0.

**Comment by tiaanduplessis** [comment]
@dragonfire1119 thanks for catching the issue. It should be fixed in v3.0.2.

**Comment by dragonfire1119** [comment]
@tiaanduplessis thanks for the fast fix! Going to try it out soon!
