### ISSUE TITLE
checkboxStyle not working.

### ISSUE THREAD

**Issue by lukasz-gorski** [tiaanduplessis/react-native-modest-checkbox#2]
Hello, i have problems with checkboxStyle, its not working... I need to change chechbox image size to 60x33, but its not working. Any of styles is not working, even if im not using image as checkbox..
`<CheckBox
		    checkboxStyle={{height: 33, width: 60}}
                    labelBefore={true}
                    label='AUTO STREAM IMAGES'
                    containerStyle={styles.checkbox}
                    labelStyle={styles.label}
                    checkedImage={require('../../img/checkboxbig_ok.png')}
                    uncheckedImage={require('../../img/checkboxbig.png')} 
                    />`

**Comment by tiaanduplessis** [comment]
@lukasz-gorski try with `checkBoxStyle` instead of `checkboxStyle`

**Comment by tiaanduplessis** [comment]
@lukasz-gorski with the [latest release](https://github.com/tiaanduplessis/react-native-modest-checkbox/releases/tag/2.0.0) the API has been changed to `checkboxStyle`
