### ISSUE TITLE
Impossible to update state

### ISSUE THREAD

**Issue by maxfadeev** [tiaanduplessis/react-native-modest-checkbox#9]
Looks like when I update a state of checkbox, it can't be updated.
For example, if I click "Uncheck all" to change state of all checkboxes.

**Comment by maxfadeev** [comment]
As I see in the repo, you already fixed that, but didn't tagged. Latest 2.0 tag doesn't have that fix

**Comment by maxfadeev** [comment]
Thanks @tiaanduplessis, it works now

**Comment by tiaanduplessis** [comment]
@maxfadeev no problem 👍, you too
